<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4020.12">
  <POU Name="P_InitializeSystem" Id="{9d3c29d9-26b1-439a-a183-dcf5570d24b6}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM P_InitializeSystem
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="P_InitializeSystem">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>